<a href="https://colab.research.google.com/github/Dracomp89/Eduardo-Phillips---202115611-Juan-Esteban-Sanchez---202213476/blob/main/Tarea4/Tarea_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Punto 3

In [6]:
import numpy as np

class SistemaLineal:
    def __init__(self, A, b, tol=1e-10, max_iter=1000):

        self.A = np.array(A, dtype=float)
        self.b = np.array(b, dtype=float)
        self.tol = tol
        self.max_iter = max_iter
        self.n = len(b)

    def jacobi(self):

        x_old = np.zeros_like(self.b)
        x_new = np.zeros_like(self.b)
        iteraciones = 0

        for k in range(self.max_iter):
            iteraciones += 1
            for i in range(self.n):
                sumatoria = sum(self.A[i, j] * x_old[j] for j in range(self.n) if j != i)
                x_new[i] = (self.b[i] - sumatoria) / self.A[i, i]


            if np.linalg.norm(x_new - x_old, ord=np.inf) < self.tol:
                print(f"Jacobi convergió en {iteraciones} iteraciones.")
                return x_new, iteraciones

            x_old = x_new.copy()

        print("Jacobi no convergió en el número máximo de iteraciones.")
        return x_new, iteraciones

    def gauss_seidel(self):

        x = np.zeros_like(self.b)
        iteraciones = 0

        for k in range(self.max_iter):
            iteraciones += 1
            x_old = x.copy()

            for i in range(self.n):
                sumatoria1 = sum(self.A[i, j] * x[j] for j in range(i))
                sumatoria2 = sum(self.A[i, j] * x_old[j] for j in range(i + 1, self.n))
                x[i] = (self.b[i] - sumatoria1 - sumatoria2) / self.A[i, i]


            if np.linalg.norm(x - x_old, ord=np.inf) < self.tol:
                print(f"Gauss-Seidel convergió en {iteraciones} iteraciones.")
                return x, iteraciones

        print("Gauss-Seidel no convergió en el número máximo de iteraciones.")
        return x, iteraciones


Punto 4

In [18]:
import numpy as np

def multiplicar_matrices(A, B):


    filas_A = len(A)
    columnas_A = len(A[0])
    filas_B = len(B)
    columnas_B = len(B[0])


    if columnas_A != filas_B:
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")


    C = np.zeros((filas_A, columnas_B))


    for i in range(filas_A):
        for j in range(columnas_B):
            for k in range(columnas_A):
                C[i][j] += A[i][k] * B[k][j]

    return C


A = [
    [1, 0, 0],
    [5, 1, 0],
    [-2, 3, 1]
]

B = [
    [4, -2, 1],
    [0, 3, 7],
    [0, 0, 2]
]


resultado = multiplicar_matrices(A, B)
print("El resultado de la multiplicación AB es:")
print(resultado)


El resultado de la multiplicación AB es:
[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]


Punto 5

5.

$
\begin{aligned} A_{00}x_0 &= b_0, \\ A_{10}x_0 + A_{11}x_1 &= b_1, \\ A_{20}x_0 + A_{21}x_1 + A_{22}x_2 &= b_2, \\ &\vdots \\ A_{i0}x_0 + A_{i1}x_1 + \dots + A_{ii}x_i &= b_i. \end{aligned}
$



Primera Ecuación ($i=0$):

$A_{00}x_0 = b_0$

Como $A_{00} \neq 0$ despejamos $x_0$:

$x_0 = \frac{b_0}{A_{00}}$
Segunda Ecuación ($i=1$):
$A_{10}x_0 + A_{11}x_1 = b_1$

Usando el valor de $x_0$ obtenido anteriormente, despejamos $x_1$:

$x_1 = \frac{b_1 - A_{10}x_0}{A_{11}}$

Tercera Ecuación ($i=2$):
$A_{20}x_0 + A_{21}x_1 + A_{22}x_2 = b_2$

Sustituyendo los valores de $x_0$ y $x_1$, despejamos $x_2$:

$x_2 = \frac{b_2 - (A_{20}x_0 + A_{21}x_1)}{A_{22}}$

i-ésima ecuación ($i=i$)
$A_{i0}x_0 + A_{i1}x_1 + \dots + A_{ii}x_i = b_i$

Despejamos $x_i$:

$x_i = \frac{b_i - \left( \sum_{j=0}^{i-1} A_{ij}x_j \right)}{A_{ii}}$

Punto 6

6.

$\begin{aligned} A_{nn}x_n &= b_n, \\ A_{(n-1)(n-1)}x_{n-1} + A_{(n-1)n}x_n &= b_{n-1}, \\ A_{(n-2)(n-2)}x_{n-2} + A_{(n-2)(n-1)}x_{n-1} + A_{(n-2)n}x_n &= b_{n-2}, \\ &\vdots \\ A_{00}x_0 + A_{01}x_1 + \dots + A_{0n}x_n &= b_0. \end{aligned}$


Última ecuación $i=n$:

$A_{nn}x_n = b_n$

Como $A_{nn} \neq 0$, despejamos $x_n$:

$x_n = \frac{b_n}{A_{nn}}$

Ecuación para $i=n−1$

$A_{(n-1)(n-1)}x_{n-1} + A_{(n-1)n}x_n = b_{n-1}$

Usando el valor de $x_n$ calculado anteriormente, despejamos $x_{n-1}$:

$x_{n-1} = \frac{b_{n-1} - A_{(n-1)n}x_n}{A_{(n-1)(n-1)}}$

Ecuación para $i=n−2$:

$A_{(n-2)(n-2)}x_{n-2} + A_{(n-2)(n-1)}x_{n-1} + A_{(n-2)n}x_n = b_{n-2}$

Sustituyendo los valores de $x_{n-1}$ y $x_n$, despejamos $x_{n-2}$:

$x_{n-2} = \frac{b_{n-2} - \left( A_{(n-2)(n-1)}x_{n-1} + A_{(n-2)n}x_n \right)}{A_{(n-2)(n-2)}}$

ecuación para $i$:

$A_{ii}x_i + \sum_{j=i+1}^{n} A_{ij}x_j = b_i$

Usando los valores ya calculados de $x_{i+1}, x_{i+2}, \dots, x_n$ , despejamos $x_i$:

$x_i = \frac{b_i - \sum_{j=i+1}^{n} A_{ij}x_j}{A_{ii}}$

Punto 8

$A = \begin{pmatrix} 4 & -2 & 1 \\ 20 & -7 & 12 \\ -8 & 13 & 17 \end{pmatrix}$

$L = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}, \quad U = A = \begin{pmatrix} 4 & -2 & 1 \\ 20 & -7 & 12 \\ -8 & 13 & 17 \end{pmatrix}$

Primer columna

1.Eliminar el elemento $U_{21}$ (en la fila 2, columna 1):

Restamos $5$ veces la primera fila de la segunda fila:

$\text{Fila 2} = \text{Fila 2} - 5 *\text{Fila 1}$

$L = \begin{pmatrix} 1 & 0 & 0 \\ 5 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}, \quad U = \begin{pmatrix} 4 & -2 & 1 \\ 0 & -7 & 12 \\ -8 & 13 & 17 \end{pmatrix}$

2.Eliminar el elemento $U_{31}$ (en la fila 3, columna 1):



Restamos $-2$ veces la primera fila de la tercera fila:

$\text{Fila 3} = \text{Fila 3} + 2\text{Fila 1}$


$L = \begin{pmatrix} 1 & 0 & 0 \\ 5 & 1 & 0 \\ -2 & 0 & 1 \end{pmatrix}, \quad U = \begin{pmatrix} 4 & -2 & 1 \\ 0 & 3 & 7 \\ 0 & 9 & 19 \end{pmatrix}$


Segunda columna


1.Eliminar el elemento $U_{32}$:

Restamos $3$ veces la segunda fila de la tercera fila:

$\text{Fila 3} = \text{Fila 3} - 3 \times \text{Fila 2}$

$L = \begin{pmatrix} 1 & 0 & 0 \\ 5 & 1 & 0 \\ -2 & 3 & 1 \end{pmatrix}, \quad U = \begin{pmatrix} 4 & -2 & 1 \\ 0 & 3 & 7 \\ 0 & 0 & -2 \end{pmatrix}$

Estas son las matrices LU esperadas

Punto 10

Punto 12

In [25]:
import numpy as np

def metodo_newton_raphson(sistema_funciones, jacobiano, valor_inicial, tolerancia=1e-8, max_iteraciones=100):
    solucion_actual = valor_inicial.copy()
    for iteracion in range(max_iteraciones):
        valor_funciones = sistema_funciones(solucion_actual)
        valor_jacobiano = jacobiano(solucion_actual)

        try:
            cambio = np.linalg.solve(valor_jacobiano, -valor_funciones)
        except np.linalg.LinAlgError:
            print("Error: Jacobiano singular.")
            return solucion_actual

        solucion_actual += cambio

        if np.linalg.norm(cambio, ord=2) < tolerancia:
            print(f"Convergencia alcanzada en {iteracion + 1} iteraciones.")
            return solucion_actual
    print("No se alcanzó la convergencia.")
    return solucion_actual

def ecuacion_1(solucion):
    x1, x2 = solucion
    return np.log(2 * x1 + 2 * x2) - np.sin(x1 * x2) - np.log(2) - np.log(np.pi)

def ecuacion_2(solucion):
    x1, x2 = solucion
    return np.exp(x1 - x2) + np.cos(x1 * x2)

def sistema_ecuaciones(solucion):
    return np.array([ecuacion_1(solucion), ecuacion_2(solucion)])

def jacobiano_sistema(solucion):
    x1, x2 = solucion
    denominador = 2 * x1 + 2 * x2
    J11 = (2 * x1) / denominador - x2 * np.cos(x1 * x2)
    J12 = (2 * x2) / denominador - x1 * np.cos(x1 * x2)
    J21 = np.exp(x1 - x2) - x2 * np.sin(x1 * x2)
    J22 = -np.exp(x1 - x2) - x1 * np.sin(x1 * x2)
    return np.array([[J11, J12], [J21, J22]])

valor_inicial = np.array([2.0, 2.0])

solucion_newton_raphson = metodo_newton_raphson(sistema_ecuaciones, jacobiano_sistema, valor_inicial)
print("Solución (Newton-Raphson):", solucion_newton_raphson)

def metodo_descenso_gradiente(sistema_funciones, jacobiano, valor_inicial, tasa_aprendizaje=0.01, tolerancia=1e-8, max_iteraciones=1000):
    solucion_actual = valor_inicial.copy()
    for iteracion in range(max_iteraciones):
        valor_funciones = sistema_funciones(solucion_actual)
        gradiente = jacobiano(solucion_actual).T @ valor_funciones

        nueva_solucion = solucion_actual - tasa_aprendizaje * gradiente

        if np.linalg.norm(nueva_solucion - solucion_actual, ord=2) < tolerancia:
            print(f"Convergencia alcanzada en {iteracion + 1} iteraciones.")
            return nueva_solucion
        solucion_actual = nueva_solucion
    print("No se alcanzó la convergencia.")
    return solucion_actual

solucion_descenso_gradiente = metodo_descenso_gradiente(sistema_ecuaciones, jacobiano_sistema, valor_inicial)
print("Solución (Descenso del Gradiente):", solucion_descenso_gradiente)

def sistema_ecuaciones_2(solucion):
    x1, x2, x3 = solucion
    f1 = 6 * x1 - 2 * np.cos(x2 * x3) - 1
    f2 = 9 * x2 + np.sqrt(x1**2 + np.sin(x3) + 1.06) + 0.9
    f3 = 60 * x3 + 3 * np.exp(-x1 * x2) + 10 * np.pi - 3
    return np.array([f1, f2, f3])

def jacobiano_sistema_2(solucion):
    x1, x2, x3 = solucion
    J = np.zeros((3, 3))
    J[0, 0] = 6
    J[0, 1] = 2 * x3 * np.sin(x2 * x3)
    J[0, 2] = 2 * x2 * np.sin


Convergencia alcanzada en 9 iteraciones.
Solución (Newton-Raphson): [1.74012179 1.74555204]
Convergencia alcanzada en 531 iteraciones.
Solución (Descenso del Gradiente): [1.74012142 1.74555238]


Punto 13

In [19]:
import numpy as np

def jacobiano_cuarto_orden(f, x, h=0.01):

    n = len(x)
    m = len(f(x))
    J = np.zeros((m, n))

    for i in range(n):

        e = np.zeros_like(x)
        e[i] = 1

        J[:, i] = (-f(x + 2*h*e) + 8*f(x + h*e) - 8*f(x - h*e) + f(x - 2*h*e)) / (12 * h)

    return J

def F(x):
    return np.array([x[0]**2 + x[1]**2 + x[2]**2, x[0] * x[1] * x[2], np.sin(x[0] + x[1] + x[2])])

x = np.array([0.5, 0.5, 0.5])

J_cuarto_orden = jacobiano_cuarto_orden(F, x, h=0.01)
print("Jacobiano de cuarto orden en x:", J_cuarto_orden)
def jacobiano_segundo_orden(f, x, h=0.01):

    n = len(x)
    m = len(f(x))
    J = np.zeros((m, n))

    for i in range(n):
        e = np.zeros_like(x)
        e[i] = 1

        J[:, i] = (f(x + h*e) - f(x - h*e)) / (2 * h)

    return J


J_segundo_orden = jacobiano_segundo_orden(F, x, h=0.01)
print("Jacobiano de segundo orden en x:", J_segundo_orden)
def comparar_jacobianos(f, x, h_values):

    for h in h_values:
        J_2 = jacobiano_segundo_orden(f, x, h)
        J_4 = jacobiano_cuarto_orden(f, x, h)
        error = np.linalg.norm(J_2 - J_4)
        print(f"h = {h}: error entre segundo y cuarto orden = {error}")

h_values = [0.1, 0.05, 0.01, 0.005, 0.001]

comparar_jacobianos(F, x, h_values)


Jacobiano de cuarto orden en x: [[1.        1.        1.       ]
 [0.25      0.25      0.25     ]
 [0.0707372 0.0707372 0.0707372]]
Jacobiano de segundo orden en x: [[1.         1.         1.        ]
 [0.25       0.25       0.25      ]
 [0.07073602 0.07073602 0.07073602]]
h = 0.1: error entre segundo y cuarto orden = 0.0002036907205570962
h = 0.05: error entre segundo y cuarto orden = 5.1018279644268366e-05
h = 0.01: error entre segundo y cuarto orden = 2.0419560773415795e-06
h = 0.005: error entre segundo y cuarto orden = 5.104985928892588e-07
h = 0.001: error entre segundo y cuarto orden = 2.042010102166809e-08


Punto 14

In [22]:
import sympy as sp

matriz_rotacion_x = sp.Matrix([[0, 0, 0], [0, 0, -1], [0, 1, 0]])
matriz_rotacion_y = sp.Matrix([[0, 0, 1], [0, 0, 0], [-1, 0, 0]])
matriz_rotacion_z = sp.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]])

def simbolo_levicivita(i, j, k):
    if (i, j, k) in [(1, 2, 3), (2, 3, 1), (3, 1, 2)]:
        return 1
    elif (i, j, k) in [(3, 2, 1), (1, 3, 2), (2, 1, 3)]:
        return -1
    else:
        return 0

conmutador_xy = matriz_rotacion_x * matriz_rotacion_y - matriz_rotacion_y * matriz_rotacion_x
conmutador_xz = matriz_rotacion_x * matriz_rotacion_z - matriz_rotacion_z * matriz_rotacion_x
conmutador_yz = matriz_rotacion_y * matriz_rotacion_z - matriz_rotacion_z * matriz_rotacion_y

print("[J_x, J_y] =", conmutador_xy, "Símbolo Levi-Civita:", simbolo_levicivita(1, 2, 3))
print("[J_x, J_z] =", conmutador_xz, "Símbolo Levi-Civita:", simbolo_levicivita(2, 1, 3))
print("[J_y, J_z] =", conmutador_yz, "Símbolo Levi-Civita:", simbolo_levicivita(2, 2, 18))


[J_x, J_y] = Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]]) Símbolo Levi-Civita: 1
[J_x, J_z] = Matrix([[0, 0, -1], [0, 0, 0], [1, 0, 0]]) Símbolo Levi-Civita: -1
[J_y, J_z] = Matrix([[0, 0, 0], [0, 0, -1], [0, 1, 0]]) Símbolo Levi-Civita: 0
