<a href="https://colab.research.google.com/github/Dracomp89/Eduardo-Phillips---202115611-Juan-Esteban-Sanchez---202213476/blob/main/Tarea5/Tarea_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Punto 3

In [6]:
import numpy as np

class SistemaLineal:
    def __init__(self, A, b, tol=1e-10, max_iter=1000):
        """
        Constructor de la clase que recibe la matriz de coeficientes (A) y el vector independiente (b).
        Parámetros:
        - A: Matriz de coeficientes.
        - b: Vector de términos independientes.
        - tol: Tolerancia para el criterio de convergencia.
        - max_iter: Máximo número de iteraciones permitidas.
        """
        self.A = np.array(A, dtype=float)
        self.b = np.array(b, dtype=float)
        self.tol = tol
        self.max_iter = max_iter
        self.n = len(b)  # número de ecuaciones

    def jacobi(self):
        """
        Resuelve el sistema usando el método iterativo de Jacobi.
        Devuelve la solución aproximada y el número de iteraciones.
        """
        x_old = np.zeros_like(self.b)  # inicialización en cero
        x_new = np.zeros_like(self.b)  # vector de la nueva solución
        iteraciones = 0

        for k in range(self.max_iter):
            iteraciones += 1
            for i in range(self.n):
                sumatoria = sum(self.A[i, j] * x_old[j] for j in range(self.n) if j != i)
                x_new[i] = (self.b[i] - sumatoria) / self.A[i, i]

            # Verificar la convergencia
            if np.linalg.norm(x_new - x_old, ord=np.inf) < self.tol:
                print(f"Jacobi convergió en {iteraciones} iteraciones.")
                return x_new, iteraciones

            x_old = x_new.copy()

        print("Jacobi no convergió en el número máximo de iteraciones.")
        return x_new, iteraciones

    def gauss_seidel(self):
        """
        Resuelve el sistema usando el método iterativo de Gauss-Seidel.
        Devuelve la solución aproximada y el número de iteraciones.
        """
        x = np.zeros_like(self.b)  # inicialización en cero
        iteraciones = 0

        for k in range(self.max_iter):
            iteraciones += 1
            x_old = x.copy()

            for i in range(self.n):
                sumatoria1 = sum(self.A[i, j] * x[j] for j in range(i))  # ya calculados
                sumatoria2 = sum(self.A[i, j] * x_old[j] for j in range(i + 1, self.n))  # pendientes
                x[i] = (self.b[i] - sumatoria1 - sumatoria2) / self.A[i, i]

            # Verificar la convergencia
            if np.linalg.norm(x - x_old, ord=np.inf) < self.tol:
                print(f"Gauss-Seidel convergió en {iteraciones} iteraciones.")
                return x, iteraciones

        print("Gauss-Seidel no convergió en el número máximo de iteraciones.")
        return x, iteraciones


Punto 4

In [7]:
import numpy as np

def multiplicar_matrices(A, B):
    """
    Multiplica dos matrices A y B.
    Parámetros:
    - A: Matriz de dimensiones m x n.
    - B: Matriz de dimensiones n x p.

    Retorna:
    - C: Matriz resultado de la multiplicación A x B.
    """
    # Obtener las dimensiones de las matrices
    filas_A = len(A)
    columnas_A = len(A[0])
    filas_B = len(B)
    columnas_B = len(B[0])

    # Verificar si la multiplicación es posible (columnas de A = filas de B)
    if columnas_A != filas_B:
        raise ValueError("El número de columnas de A debe ser igual al número de filas de B")

    # Crear la matriz resultante C con ceros
    C = np.zeros((filas_A, columnas_B))

    # Realizar la multiplicación de matrices
    for i in range(filas_A):
        for j in range(columnas_B):
            for k in range(columnas_A):  # o filas_B, dado que son iguales
                C[i][j] += A[i][k] * B[k][j]

    return C

# Definición de las matrices A y B
A = [
    [1, 0, 0],
    [5, 1, 0],
    [-2, 3, 1]
]

B = [
    [4, -2, 1],
    [0, 3, 7],
    [0, 0, 2]
]

# Calcular el producto AB
resultado = multiplicar_matrices(A, B)
print("El resultado de la multiplicación AB es:")
print(resultado)


El resultado de la multiplicación AB es:
[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]


Punto 5

5.

$
\begin{aligned} A_{00}x_0 &= b_0, \\ A_{10}x_0 + A_{11}x_1 &= b_1, \\ A_{20}x_0 + A_{21}x_1 + A_{22}x_2 &= b_2, \\ &\vdots \\ A_{i0}x_0 + A_{i1}x_1 + \dots + A_{ii}x_i &= b_i. \end{aligned}
$



Primera Ecuación ($i=0$):

$A_{00}x_0 = b_0$

Como $A_{00} \neq 0$ despejamos $x_0$:

$x_0 = \frac{b_0}{A_{00}}$
Segunda Ecuación ($i=1$):
$A_{10}x_0 + A_{11}x_1 = b_1$

Usando el valor de $x_0$ obtenido anteriormente, despejamos $x_1$:

$x_1 = \frac{b_1 - A_{10}x_0}{A_{11}}$

Tercera Ecuación ($i=2$):
$A_{20}x_0 + A_{21}x_1 + A_{22}x_2 = b_2$

Sustituyendo los valores de $x_0$ y $x_1$, despejamos $x_2$:

$x_2 = \frac{b_2 - (A_{20}x_0 + A_{21}x_1)}{A_{22}}$

i-ésima ecuación ($i=i$)
$A_{i0}x_0 + A_{i1}x_1 + \dots + A_{ii}x_i = b_i$

Despejamos $x_i$:

$x_i = \frac{b_i - \left( \sum_{j=0}^{i-1} A_{ij}x_j \right)}{A_{ii}}$

Punto 6

6.

$\begin{aligned} A_{nn}x_n &= b_n, \\ A_{(n-1)(n-1)}x_{n-1} + A_{(n-1)n}x_n &= b_{n-1}, \\ A_{(n-2)(n-2)}x_{n-2} + A_{(n-2)(n-1)}x_{n-1} + A_{(n-2)n}x_n &= b_{n-2}, \\ &\vdots \\ A_{00}x_0 + A_{01}x_1 + \dots + A_{0n}x_n &= b_0. \end{aligned}$


Última ecuación $i=n$:

$A_{nn}x_n = b_n$

Como $A_{nn} \neq 0$, despejamos $x_n$:

$x_n = \frac{b_n}{A_{nn}}$

Ecuación para $i=n−1$

$A_{(n-1)(n-1)}x_{n-1} + A_{(n-1)n}x_n = b_{n-1}$

Usando el valor de $x_n$ calculado anteriormente, despejamos $x_{n-1}$:

$x_{n-1} = \frac{b_{n-1} - A_{(n-1)n}x_n}{A_{(n-1)(n-1)}}$

Ecuación para $i=n−2$:

$A_{(n-2)(n-2)}x_{n-2} + A_{(n-2)(n-1)}x_{n-1} + A_{(n-2)n}x_n = b_{n-2}$

Sustituyendo los valores de $x_{n-1}$ y $x_n$, despejamos $x_{n-2}$:

$x_{n-2} = \frac{b_{n-2} - \left( A_{(n-2)(n-1)}x_{n-1} + A_{(n-2)n}x_n \right)}{A_{(n-2)(n-2)}}$

ecuación para $i$:

$A_{ii}x_i + \sum_{j=i+1}^{n} A_{ij}x_j = b_i$

Usando los valores ya calculados de $x_{i+1}, x_{i+2}, \dots, x_n$ , despejamos $x_i$:

$x_i = \frac{b_i - \sum_{j=i+1}^{n} A_{ij}x_j}{A_{ii}}$

Punto 10

Punto 12

Punto 13

In [17]:
import numpy as np

def jacobiano_cuarto_orden(f, x, h=0.01):
    """
    Estima el Jacobiano de la función vectorial f en el punto x
    usando un operador de derivada de cuarto orden con paso h.

    f: Función vectorial a derivar (debe devolver un vector)
    x: Punto donde se evalúa el Jacobiano
    h: Paso para la aproximación
    """
    n = len(x)      # Dimensión del punto x
    m = len(f(x))   # Dimensión de la función vectorial f
    J = np.zeros((m, n))  # Inicializar la matriz Jacobiana

    for i in range(n):
        # Crear un vector de desplazamiento en la i-ésima dirección
        e = np.zeros_like(x)
        e[i] = 1

        # Estimar derivada de cuarto orden respecto a la i-ésima variable
        J[:, i] = (-f(x + 2*h*e) + 8*f(x + h*e) - 8*f(x - h*e) + f(x - 2*h*e)) / (12 * h)

    return J

# Ejemplo de uso con una función vectorial
def F(x):
    return np.array([x[0]**2 + x[1]**2 + x[2]**2, x[0] * x[1] * x[2], np.sin(x[0] + x[1] + x[2])])

# Punto de evaluación
x = np.array([0.5, 0.5, 0.5])

# Estimación del Jacobiano en el punto x
J_cuarto_orden = jacobiano_cuarto_orden(F, x, h=0.01)
print("Jacobiano de cuarto orden en x:", J_cuarto_orden)
def jacobiano_segundo_orden(f, x, h=0.01):
    """
    Estima el Jacobiano de la función vectorial f en el punto x
    usando un operador de derivada de segundo orden con paso h.

    f: Función vectorial a derivar (debe devolver un vector)
    x: Punto donde se evalúa el Jacobiano
    h: Paso para la aproximación
    """
    n = len(x)
    m = len(f(x))
    J = np.zeros((m, n))

    for i in range(n):
        e = np.zeros_like(x)
        e[i] = 1

        J[:, i] = (f(x + h*e) - f(x - h*e)) / (2 * h)

    return J

# Estimación del Jacobiano con segundo orden en el mismo punto
J_segundo_orden = jacobiano_segundo_orden(F, x, h=0.01)
print("Jacobiano de segundo orden en x:", J_segundo_orden)
def comparar_jacobianos(f, x, h_values):
    """
    Compara los Jacobianos de segundo y cuarto orden para diferentes valores de h.
    """
    for h in h_values:
        J_2 = jacobiano_segundo_orden(f, x, h)
        J_4 = jacobiano_cuarto_orden(f, x, h)
        error = np.linalg.norm(J_2 - J_4)
        print(f"h = {h}: error entre segundo y cuarto orden = {error}")

# Valores de h a probar
h_values = [0.1, 0.05, 0.01, 0.005, 0.001]

comparar_jacobianos(F, x, h_values)


Jacobiano de cuarto orden en x: [[1.        1.        1.       ]
 [0.25      0.25      0.25     ]
 [0.0707372 0.0707372 0.0707372]]
Jacobiano de segundo orden en x: [[1.         1.         1.        ]
 [0.25       0.25       0.25      ]
 [0.07073602 0.07073602 0.07073602]]
h = 0.1: error entre segundo y cuarto orden = 0.0002036907205570962
h = 0.05: error entre segundo y cuarto orden = 5.1018279644268366e-05
h = 0.01: error entre segundo y cuarto orden = 2.0419560773415795e-06
h = 0.005: error entre segundo y cuarto orden = 5.104985928892588e-07
h = 0.001: error entre segundo y cuarto orden = 2.042010102166809e-08


Punto 14

In [14]:
#Punto 14
import sympy as sp

# Jx, Jy, Jz con simpy
J_x = sp.Matrix([[0, 0, 0], [0, 0, -1], [0, 1, 0]])
J_y = sp.Matrix([[0, 0, 1], [0, 0, 0], [-1, 0, 0]])
J_z = sp.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]])

def levicivita(i, j, k):
    if (i, j, k) in [(1, 2, 3), (2, 3, 1), (3, 1, 2)]:
        return 1
    elif (i, j, k) in [(3, 2, 1), (1, 3, 2), (2, 1, 3)]:
        return -1
    else:
        return 0

# Compute the commutators
ordenxy = J_x * J_y - J_y * J_x
ordenxz = J_x * J_z - J_z * J_x
ordenyz = J_y * J_z - J_z * J_y

print("[J_x, J_y",  ordenxy, levicivita(1, 2, 3))
print( "[J_x, J_z",  ordenxz, levicivita(2, 1, 3))
print( "[J_y, J_z",  ordenyz, levicivita(2, 2, 18))

[J_x, J_y Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]]) 1
[J_x, J_z Matrix([[0, 0, -1], [0, 0, 0], [1, 0, 0]]) -1
[J_y, J_z Matrix([[0, 0, 0], [0, 0, -1], [0, 1, 0]]) 0
